plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
    id("com.gradle.plugin-publish") version "1.2.1"
}

group = "io.github.himanshukumardutt094"
version = "1.0.0"

repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation(gradleApi())
    implementation(kotlin("stdlib"))
    
    // For JSON parsing
    implementation("com.google.code.gson:gson:2.10.1")
    
    // For bytecode analysis (annotation scanning)
    implementation("org.ow2.asm:asm:9.6")
    
    // For type-safe Kotlin code generation
    implementation("com.squareup:kotlinpoet:1.16.0")
    
    // Testing
    testImplementation("junit:junit:4.13.2")
    testImplementation(gradleTestKit())
}

gradlePlugin {
    website = "https://github.com/HimanshuKumarDutt094/tiger-modules"
    vcsUrl = "https://github.com/HimanshuKumarDutt094/tiger-modules.git"
    
    plugins {
        create("tigerModuleAutolink") {
            id = "io.github.himanshukumardutt094.tiger-autolink"
            implementationClass = "com.tigermodule.autolink.TigerModuleAutolinkPlugin"
            displayName = "TigerModule Autolink Plugin"
            description = "Unified Gradle plugin for TigerModule extension autolink. Discovers extensions in node_modules, generates registry code, and integrates native modules automatically. Apply in both settings.gradle.kts and build.gradle.kts."
            tags = listOf("tigermodule", "autolink", "native-modules", "android", "lynxjs", "codegen", "discovery")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
    }
}

// Generate version constants for use in Kotlin code
val generateVersionTask = tasks.register("generateVersion") {
    val outputDir = layout.buildDirectory.dir("generated/source/version/main/kotlin")
    outputs.dir(outputDir)
    
    doLast {
        val versionFile = outputDir.get().asFile.resolve("com/tigermodule/autolink/BuildConfig.kt")
        versionFile.parentFile.mkdirs()
        versionFile.writeText("""
            package com.tigermodule.autolink
            
            /**
             * Build configuration constants
             * Auto-generated by Gradle build
             */
            object BuildConfig {
                const val VERSION = "${project.version}"
                const val GROUP = "${project.group}"
            }
        """.trimIndent())
    }
}

sourceSets {
    main {
        kotlin {
            srcDir(generateVersionTask.map { it.outputs.files.singleFile })
        }
    }
}

tasks.compileKotlin {
    dependsOn(generateVersionTask)
}

publishing {
    repositories {
        maven {
            name = "local"
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}
