plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
    id("com.gradle.plugin-publish") version "1.2.1"
}

group = "io.github.himanshukumardutt094"
version = "1.0.0"

repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation(gradleApi())
    implementation(kotlin("stdlib"))
    
    // For JSON parsing
    implementation("com.google.code.gson:gson:2.10.1")
    
    // Testing
    testImplementation("junit:junit:4.13.2")
    testImplementation(gradleTestKit())
}

gradlePlugin {
    website = "https://github.com/HimanshuKumarDutt094/tiger-modules"
    vcsUrl = "https://github.com/HimanshuKumarDutt094/tiger-modules.git"
    
    plugins {
        create("tigerModuleExtensionSettings") {
            id = "io.github.himanshukumardutt094.extension-settings"
            implementationClass = "com.tigermodule.autolink.TigerModuleExtensionSettingsPlugin"
            displayName = "TigerModule Extension Settings Plugin"
            description = "Gradle settings plugin for discovering and configuring TigerModule extensions in node_modules. Automatically scans for tiger.config.json files and prepares extensions for integration."
            tags = listOf("tigermodule", "autolink", "native-modules", "android", "settings", "discovery")
        }
        create("tigerModuleExtensionBuild") {
            id = "io.github.himanshukumardutt094.extension-build"
            implementationClass = "com.tigermodule.autolink.TigerModuleExtensionBuildPlugin"
            displayName = "TigerModule Extension Build Plugin"
            description = "Gradle build plugin for integrating TigerModule extensions into Android projects. Generates registry code and copies native source files automatically."
            tags = listOf("tigermodule", "autolink", "native-modules", "android", "build", "codegen")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
    }
}

// Generate version constants for use in Kotlin code
val generateVersionTask = tasks.register("generateVersion") {
    val outputDir = layout.buildDirectory.dir("generated/source/version/main/kotlin")
    outputs.dir(outputDir)
    
    doLast {
        val versionFile = outputDir.get().asFile.resolve("com/tigermodule/autolink/BuildConfig.kt")
        versionFile.parentFile.mkdirs()
        versionFile.writeText("""
            package com.tigermodule.autolink
            
            /**
             * Build configuration constants
             * Auto-generated by Gradle build
             */
            object BuildConfig {
                const val VERSION = "${project.version}"
                const val GROUP = "${project.group}"
            }
        """.trimIndent())
    }
}

sourceSets {
    main {
        kotlin {
            srcDir(generateVersionTask.map { it.outputs.files.singleFile })
        }
    }
}

tasks.compileKotlin {
    dependsOn(generateVersionTask)
}

publishing {
    repositories {
        maven {
            name = "local"
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}
